#!/usr/bin/env node
// Generate CSS custom properties + a typed TS map from the suite DESIGN.md.
//
// The DESIGN.md is the single source of truth: Stitch generated 34 screens from
// a design system built out of it, so the code must not drift from it. This
// script is the only place allowed to know token names.
//
// Usage:
//   node build.mjs           write dist/tokens.css + dist/tokens.ts
//   node build.mjs --check   exit 1 if disk differs from a fresh generation
//
// ponytail: hand-rolled parser for the four shapes this file actually uses
// (flat scalars, inline flow maps, one nested block, quoted strings). Swap in a
// real YAML lib the moment the DESIGN.md grows anchors, lists, or multi-line
// scalars — not before.

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(HERE, '../../docs/PORTICO-SUITE-DESIGN.md');
const DIST = resolve(HERE, 'dist');

// --- parse -----------------------------------------------------------------

function frontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!m) throw new Error(`no YAML frontmatter in ${SRC}`);
  return m[1];
}

const unquote = (s) => {
  s = s.trim();
  if ((s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))) {
    return s.slice(1, -1);
  }
  return s;
};

// `{ a: 1px, b: 2px }` -> { a: '1px', b: '2px' }
function flowMap(s) {
  const inner = s.trim().replace(/^\{/, '').replace(/\}$/, '');
  const out = {};
  for (const pair of inner.split(',')) {
    const i = pair.indexOf(':');
    if (i < 0) continue;
    out[unquote(pair.slice(0, i))] = unquote(pair.slice(i + 1));
  }
  return out;
}

function parseBlocks(yaml) {
  const lines = yaml.split(/\r?\n/);
  const out = {};
  let current = null;
  let currentIndent = 0;

  for (const raw of lines) {
    if (!raw.trim() || raw.trim().startsWith('#')) continue;
    const indent = raw.length - raw.trimStart().length;
    const line = raw.trim();

    if (indent === 0) {
      const i = line.indexOf(':');
      if (i < 0) continue;
      const key = line.slice(0, i);
      const rest = line.slice(i + 1).trim();
      if (!rest) {
        current = out[key] = {};
        currentIndent = 0;
        continue;
      }
      current = null;
      out[key] = rest.startsWith('{') ? flowMap(rest) : unquote(rest);
      continue;
    }
    if (!current) continue;
    if (currentIndent === 0) currentIndent = indent;
    if (indent <= currentIndent && indent < currentIndent + 2) {
      // second-level key of a nested block
      const i = line.indexOf(':');
      const key = line.slice(0, i);
      const rest = line.slice(i + 1).trim();
      if (!rest) {
        current[key] = {};
        continue;
      }
      current[key] = rest.startsWith('{') ? flowMap(rest) : unquote(rest);
    }
  }
  return out;
}

// --- emit ------------------------------------------------------------------

// CSS custom properties are global, so each group needs its own prefix —
// `rounded.sm` and `spacing.sm` would otherwise both emit `--sm` and the
// later one silently wins. Colors keep their bare names because token names
// like `accent` / `surface-panel` are already unambiguous.
const CSS_GROUPS = [
  ['colors', ''],
  ['rounded', 'radius-'],
  ['spacing', 'space-'],
  ['elevation', 'elevation-'],
];

function css(blocks) {
  const lines = [
    '/* GENERATED by packages/tokens/build.mjs — do not edit.',
    ' * Source: docs/PORTICO-SUITE-DESIGN.md */',
    '',
    ':root {',
  ];
  for (const [group, prefix] of CSS_GROUPS) {
    const entries = blocks[group];
    if (!entries) continue;
    lines.push(`  /* ${group} */`);
    for (const [k, v] of Object.entries(entries)) {
      lines.push(`  --${prefix}${k}: ${v};`);
    }
  }
  // typography: font-size + weight + line-height + tracking as separate vars
  if (blocks.typography) {
    lines.push('  /* typography */');
    for (const [k, v] of Object.entries(blocks.typography)) {
      if (typeof v !== 'object') continue;
      const px = /^([\d.]+)rem$/.exec(v.fontSize || '');
      if (px) lines.push(`  --text-${k}-size: ${px[1]}rem;`);
      if (v.fontWeight) lines.push(`  --text-${k}-weight: ${v.fontWeight};`);
      if (v.lineHeight) lines.push(`  --text-${k}-leading: ${v.lineHeight};`);
      if (v.letterSpacing) lines.push(`  --text-${k}-tracking: ${v.letterSpacing};`);
      if (v.fontFamily) lines.push(`  --text-${k}-family: "${v.fontFamily}";`);
    }
  }
  lines.push('}', '');
  return lines.join('\n');
}

function ts(blocks) {
  const body = (group) => {
    const entries = blocks[group] || {};
    return Object.entries(entries)
      .map(([k, v]) => `    ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
      .join('\n');
  };
  return `// GENERATED by packages/tokens/build.mjs — do not edit.
// Source: docs/PORTICO-SUITE-DESIGN.md

export const colors = {
${body('colors')}
} as const;

export const rounded = {
${body('rounded')}
} as const;

export const spacing = {
${body('spacing')}
} as const;

export const elevation = {
${body('elevation')}
} as const;

// Shell dimensions the DESIGN-GUIDE pins down. Every shell page uses all three.
export const shell = {
  rail: 56,
  sidebar: 236,
  topbar: 48,
  listPane: 340,
  listRow: 44,
  avatar: 26,
  authCard: 380,
  hubScreen: 560,
} as const;

export type ColorToken = keyof typeof colors;
export type RadiusToken = keyof typeof rounded;
export type SpacingToken = keyof typeof spacing;
`;
}

// --- main ------------------------------------------------------------------

const blocks = parseBlocks(frontmatter(readFileSync(SRC, 'utf8')));
const tsSource = ts(blocks);
const outputs = {
  'tokens.css': css(blocks),
  'tokens.ts': tsSource,
  // Runtime entry: same values, no type annotations. Node ESM cannot
  // import .ts directly, so the preset imports ./dist/tokens.mjs.
  'tokens.mjs': tsSource
    .split('\n')
    .filter((l) => !l.match(/^export type /))
    .map((l) => l.replace(/ as const/g, '').replace(/: ColorToken/g, '').replace(/: RadiusToken/g, '').replace(/: SpacingToken/g, ''))
    .join('\n'),
};

const check = process.argv.includes('--check');
let drift = 0;

mkdirSync(DIST, { recursive: true });
for (const [name, content] of Object.entries(outputs)) {
  const path = resolve(DIST, name);
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (existing === content) {
    if (!check) console.log(`unchanged  dist/${name}`);
    continue;
  }
  if (check) {
    console.error(`DRIFT      dist/${name}`);
    drift++;
    continue;
  }
  writeFileSync(path, content);
  console.log(`wrote      dist/${name}  (${content.length} bytes)`);
}

const nColors = Object.keys(blocks.colors || {}).length;
console.log(`${nColors} colors, ${Object.keys(blocks.typography || {}).length} typography steps`);

if (check && drift) {
  console.error(`\n${drift} file(s) stale. Run: npm run tokens:build`);
  process.exit(1);
}
